Dev
stepancar-web-programming/2023-fall-lab-portfolio-tlumach-e.-d. pull request #1
Opened 2023-11-17 12:09 UTC by etlumac

2023-12-06 23:40 UTC, stepancar commented on contacts.html
> +        <p>Contact me at: your.email@example.com</p>
Давайте сделаем так, чтобы при нажатии на ваш email - открывался почтовый клиент по умолчанию

2023-12-06 23:41 UTC, stepancar commented on scripts.js
> +let currentSlide = 0;
Обратите внимание , если открыть ваш сайт, открыть devTools, можно в его консоли изменить значение 
`currentSlide ` давайте решим эту проблему

2023-12-06 23:42 UTC, stepancar requested changes
Пожалуйста, отформатируйте код, перед отправкой на ревью. 
Чтобы это не забывать, давайте добавим в проект prerttier

2023-12-28 12:42 UTC, etlumac commented on scripts.js
> +let currentSlide = 0;
Обернула код в IIFE в scripts.js, которое защитит переменные от глобального доступа через консоль devTools.

2023-12-28 12:43 UTC, etlumac commented on contacts.html
> +        <p>Contact me at: your.email@example.com</p>
Сделала.

2024-01-03 18:56 UTC, stepancar commented on styles.css
> +
Пожалуйста, отформатируйте код перед отправкой на ревью

2024-01-03 18:58 UTC, stepancar commented on styles.css
> +}
пока не понял стиль именования. Тут прослеживается разница в подходе именования. Вы используете BEM?

2024-01-03 18:58 UTC, stepancar commented on styles.css
> +}
пожалуйста, приведите код к общему виду перед отправкой на ревью

2024-01-04 03:53 UTC, stepancar requested changes
Код не готов к ревью

2024-01-14 09:59 UTC, etlumac commented on styles.css
> +}
Добрый день, почитала про BEM, постараась, чтобы названия были "блок-элемент" и подписала какой стиль к чему относится, надеюсь будет понятно!

2024-01-16 07:22 UTC, stepancar commented on p.html
> +  </head>
Давайте на защиту подключим вашу страницу к yandex metrics или google аналитике, чтобы можно было отследить, нажимал ли пользователь на  Contact me at, сколько польщтвателей и на каких страницах побывали

2024-01-16 07:22 UTC, stepancar reviewed
Жду решение мини задания для защиты

2024-01-17 23:18 UTC, stepancar commented on p.html
смотря на дерево каталогов, как понять что такое p.html?

2024-01-18 08:12 UTC, stepancar approved these changes

2024-01-18 08:12 UTC, merged